services:
  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    container_name: frontend-lideratech
    environment:
      - REACT_APP_API_URL=http://localhost:9001
    volumes:
      - ./Frontend:/app
    ports:
      - "3000:3000"
      - "9005:9005"
    networks:
      - lideratech-net

  backend:
    build:
      context: Backend
      dockerfile: Dockerfile
    container_name: backend-lideratech
    environment:
      - CORS_ADDRESS
      - DB_DRIVER=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=lideratech
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "9001:9001"
      - "9002:9002"
    networks:
      - lideratech-net
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=lideratech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lideratech-net

volumes:
  postgres_data:

networks:
  lideratech-net:
    driver: bridge
